### ISSUE TITLE
tm setup 出错了

### ISSUE THREAD

**Issue by lanceylai** [MacLeek/trackmac#3]
```
Traceback (most recent call last): 
File "/usr/local/bin/tm", line 9, in <module> 
load_entry_point('trackmac==0.0.6', 'console_scripts', 'tm')() 
File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__ 
return self.main(*args, **kwargs) 
File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main 
rv = self.invoke(ctx) 
File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke 
return _process_result(sub_ctx.command.invoke(sub_ctx)) 
File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke 
return ctx.invoke(self.callback, **ctx.params) 
File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke 
return callback(*args, **kwargs) 
File "/Library/Python/2.7/site-packages/click/decorators.py", line 17, in new_func 
return f(get_current_context(), *args, **kwargs) 
File "/Library/Python/2.7/site-packages/trackmac/main.py", line 50, in setup 
trackmac.utils.create_database() 
File "/Library/Python/2.7/site-packages/trackmac/utils.py", line 86, in create_database 
trackmac.models.BlockedApplication], safe=True) 
File "/Library/Python/2.7/site-packages/peewee.py", line 3765, in create_tables 
create_model_tables(models, fail_silently=safe) 
File "/Library/Python/2.7/site-packages/peewee.py", line 5175, in create_model_tables 
m.create_table(**create_table_kwargs) 
File "/Library/Python/2.7/site-packages/peewee.py", line 4840, in create_table 
if fail_silently and cls.table_exists(): 
File "/Library/Python/2.7/site-packages/peewee.py", line 4836, in table_exists 
return cls._meta.db_table in cls._meta.database.get_tables(**kwargs) 
File "/Library/Python/2.7/site-packages/peewee.py", line 3893, in get_tables 
'type = ? ORDER BY name;', ('table',)) 
File "/Library/Python/2.7/site-packages/peewee.py", line 3683, in execute_sql 
self.commit() 
File "/Library/Python/2.7/site-packages/peewee.py", line 3507, in __exit__ 
reraise(new_type, new_type(*exc_args), traceback) 
File "/Library/Python/2.7/site-packages/peewee.py", line 3674, in execute_sql 
cursor = self.get_cursor() 
File "/Library/Python/2.7/site-packages/peewee.py", line 3622, in get_cursor 
return self.get_conn().cursor() 
File "/Library/Python/2.7/site-packages/peewee.py", line 3615, in get_conn 
self.connect() 
File "/Library/Python/2.7/site-packages/peewee.py", line 3595, in connect 
self.initialize_connection(self._local.conn) 
File "/Library/Python/2.7/site-packages/peewee.py", line 3507, in __exit__ 
reraise(new_type, new_type(*exc_args), traceback) 
File "/Library/Python/2.7/site-packages/peewee.py", line 3593, in connect 
**self.connect_kwargs) 
File "/Library/Python/2.7/site-packages/peewee.py", line 3862, in _connect 
conn = sqlite3.connect(database, **kwargs) 
peewee.OperationalError: unable to open database file 
```

```
[Enchanting] cd ~/Library/Application\ Support/com.github.macleek.trackmac                                  10:39:06  ☁  develop ☂ ⚡
[com.github.macleek.trackmac] ls                                                                                           10:39:25
com.github.macleek.trackmac.plist track.log
```

```
```

**Comment by MacLeek** [comment]
先用ls -ld ~/Library/Application\ Support/com.github.macleek.trackmac 检查一下这个文件夹的权限是什么
然后cd 到这个目录,
在python下输入下面的代码测试一下：

```
import sqlite3
conn = sqlite3.connect('test.db')
c = conn.cursor()
conn.commit()
conn.close()
```

**Comment by lanceylai** [comment]
```
drwxr-xr-x  4 root  staff  136 Sep  9 10:04 /Users/hilen/Library/Application Support/com.github.macleek.trackmac
```

```
[com.github.macleek.trackmac] python                                                                                       11:35:55
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> conn = sqlite3.connect('test.db')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
sqlite3.OperationalError: unable to open database file
>>>
```

**Comment by MacLeek** [comment]
这个是root权限啊，改成你的用户名吧, sudo chown 你的名字 /Users/hilen/Library/Application Support/com.github.macleek.trackmac
